import pygame,sys
from pygame.locals import *

def mapa():

	CANTOESQUERDO = 0
	LADOESQ = 1
	GRASS = 2
	AGUA = 3
	LADODIR = 4
	CIMAGRAMA = 5
	BAIXOGRAMA = 6
	CANTODIREITO = 7
	CAMINHO = 8
	tilecastelo = 9
	bordatorre = 10
	cantotorre = 11
	bordabaixo = 12


	terrenos = [CANTOESQUERDO, LADOESQ, GRASS,AGUA, LADODIR, CIMAGRAMA, BAIXOGRAMA,CANTODIREITO, CAMINHO, tilecastelo, bordatorre, cantotorre, bordabaixo]
 
	textures = {
		CANTOESQUERDO: pygame.image.load('CANTOESQUERDO.png'),
		LADOESQ: pygame.image.load('LADOESQ.png'),
		GRASS: pygame.image.load('GRASS.png'),
		AGUA: pygame.image.load('AGUA.png'),
		LADODIR: pygame.image.load('LADODIR.png'),
		CIMAGRAMA: pygame.image.load('CIMAGRAMA.png'),
		BAIXOGRAMA: pygame.image.load('BAIXOGRAMA.png'),
		CANTODIREITO: pygame.image.load('CANTODIREITO.png'),
		CAMINHO: pygame.image.load('CAMINHO.png'),
		tilecastelo: pygame.image.load('tilecastelo.png'),
		bordatorre: pygame.image.load('bordatorre.png'),
		cantotorre: pygame.image.load('cantotorre.png'),
		bordabaixo: pygame.image.load('bordabaixo.png')






	}

	TILESIZE = 40
	MAPWIDTH = 40
	MAPHEIGHT = 20

	tilemap = [
	[tilecastelo, tilecastelo, tilecastelo, bordatorre, GRASS,GRASS, GRASS, AGUA, AGUA, AGUA,AGUA, AGUA,AGUA, AGUA,AGUA, AGUA, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[tilecastelo, tilecastelo, tilecastelo, bordatorre, GRASS,GRASS, GRASS, AGUA, AGUA, AGUA,AGUA, AGUA,AGUA, AGUA,AGUA, AGUA, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[tilecastelo, tilecastelo, tilecastelo, bordatorre, GRASS,GRASS, GRASS, AGUA, AGUA, AGUA,AGUA, AGUA,AGUA, AGUA,AGUA, AGUA, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[tilecastelo, tilecastelo, tilecastelo, bordatorre, GRASS,GRASS, GRASS, AGUA, AGUA, AGUA,AGUA, AGUA,AGUA, AGUA,AGUA, AGUA, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[tilecastelo, tilecastelo, tilecastelo,bordatorre, CAMINHO,CAMINHO, CAMINHO, CAMINHO, CAMINHO, CAMINHO, CAMINHO,CAMINHO, CAMINHO, CAMINHO, CAMINHO,CAMINHO, CAMINHO,CAMINHO, CAMINHO, CAMINHO, CAMINHO, CAMINHO, CAMINHO,CAMINHO, CAMINHO, CAMINHO, CAMINHO, CAMINHO, CAMINHO,CAMINHO, CAMINHO, CAMINHO, CAMINHO, CAMINHO, CAMINHO,CAMINHO, CAMINHO, CAMINHO, CAMINHO, CAMINHO],
	[tilecastelo, tilecastelo, tilecastelo, bordatorre, GRASS,GRASS, GRASS, AGUA, AGUA, AGUA,AGUA, AGUA,AGUA, AGUA,AGUA, AGUA, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[tilecastelo, tilecastelo, tilecastelo, bordatorre, GRASS,GRASS, GRASS, AGUA, AGUA, AGUA,AGUA, AGUA,AGUA, AGUA,AGUA, AGUA, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[tilecastelo, tilecastelo, tilecastelo, bordatorre, GRASS,GRASS, GRASS, AGUA, AGUA, AGUA,AGUA, AGUA,AGUA, AGUA,AGUA, AGUA, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[tilecastelo, tilecastelo, tilecastelo, bordatorre, GRASS,GRASS, GRASS, AGUA, AGUA, AGUA,AGUA, AGUA,AGUA, AGUA,AGUA, AGUA, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[tilecastelo, tilecastelo, tilecastelo, bordatorre, GRASS,GRASS, GRASS, AGUA, AGUA, AGUA,AGUA, AGUA,AGUA, AGUA,AGUA, AGUA, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[tilecastelo, tilecastelo, tilecastelo, bordatorre, GRASS,GRASS, GRASS,AGUA, AGUA, AGUA,AGUA, AGUA,AGUA, AGUA,AGUA, AGUA, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[tilecastelo, tilecastelo, tilecastelo, bordatorre, GRASS,GRASS, GRASS, AGUA, AGUA, AGUA,AGUA, AGUA,AGUA, AGUA,AGUA, AGUA, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[tilecastelo, tilecastelo, tilecastelo, bordatorre, GRASS,GRASS, GRASS, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[bordabaixo, bordabaixo, bordabaixo, cantotorre, GRASS,GRASS, GRASS, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[GRASS, GRASS,GRASS, GRASS, GRASS,GRASS, GRASS, AGUA, AGUA,AGUA,AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[GRASS, GRASS,GRASS, GRASS, GRASS,GRASS, GRASS, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[GRASS, GRASS,GRASS, GRASS, GRASS,GRASS, GRASS, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA],
	[GRASS, GRASS,GRASS, GRASS, GRASS,GRASS, GRASS, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA],
	[GRASS, GRASS,GRASS, GRASS, GRASS,GRASS, GRASS, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA],
	[GRASS, GRASS,GRASS, GRASS, GRASS,GRASS, GRASS, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA],

	]

	DISPLAYSURF = pygame.display.set_mode((MAPWIDTH*TILESIZE, MAPHEIGHT*TILESIZE))
	pygame.display.set_caption('Tower Defense')

	while True:

		for event in pygame.event.get():
			if event.type == QUIT:
				pygame.quit()
				sys.exit()

		for row in range(MAPHEIGHT):

			for column in range(MAPWIDTH):
				DISPLAYSURF.blit(textures[tilemap[row][column]], (column*TILESIZE,row*TILESIZE))

		pygame.display.update()
mapa()
#DISPLAYSURF.blit(self.textures[tilemap[row][column]], (column*TILESIZE,row*TILESIZE))
#pygame.display.set_caption('Tower Defense')